#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "subject类型："
declare rulesSubject=(
    "feat"[="新功能"]
    "fix"[="bug修复"]
    "docs"[="文档更新，仅仅修改了文档，如readme.md"]
    "test"[="测试用例，包括单元测试、集成测试"]
    "style"[="样式变动，仅仅是对格式进行修改，如逗号、缩进、空格等。不改变代码逻辑"]
    "perf"[="优化相关，如提升性能、用户体验等"]
    "upd"[="修改"]
    "del"[="删除"]
    "refactor"[="代码重构，没有新增功能或修复bug"]
    "revert"[="回滚某个更早之前的提交"]
    "chore"[="改变构建流程、或者增加依赖库、工具等"]
)
echo "${rulesSubject[*]} \n"
npx --no-install commitlint --edit "$1"
